// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warframe_Inventory.Data;

#nullable disable

namespace Warframe_Inventory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Warframe_Inventory.Entities.Warframe", b =>
                {
                    b.Property<int>("WarframeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blueprints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chassis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Neuroptics")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Systems")
                        .HasColumnType("INTEGER");

                    b.HasKey("WarframeId");

                    b.ToTable("Warframes");

                    b.HasData(
                        new
                        {
                            WarframeId = 1,
                            Blueprints = 1,
                            Chassis = 1,
                            Name = "Excalibur",
                            Neuroptics = 1,
                            Systems = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
